addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.0.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.5.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.6")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.3.21")
addSbtPlugin("org.ensime"                % "sbt-ensime"          % "2.5.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-release-early"   % "2.1.1")
